### ISSUE TITLE
from gene name, get frame-id and its position

### ISSUE THREAD

**Issue by runfish5** [networkbiolab/PythonCyc#1]
I want to use the ecocyc reference genome to find genome positions of a list of gene names.
`l_genes = ["Pcn", "pyrH", "araJ", "ybcM/ylcH", "aroH", "rpoD", "malt", "xylR", "rpoB", "pgi", "aadA/fdh"]`

The best help resource for pythoncyc doesn't help me with this particular task.https://github.com/networkbiolab/PythonCyc/blob/master/examples/Operations_on_Proteins_and_Protein_Complexes.ipynb

`pythoncyc.PGDB.may_be_frameid('crp')`
returns:
`type object 'PGDB' has no attribute 'may_be_frameid'`

**How can I convert KEGG or other standard/common gene names to frame-ids?**

**Comment by glucksfall** [comment]
Hi @raven44099,

You need to query the IDs that are in the internal database. So, first step is get those IDs:
```
ecoli = pythoncyc.select_organism(u'|ECOLI|')
genes = [x.frameid for x in ecoli.genes.instances]
```
Next, query each ID to get the common name and build a dictionary, so you can query the common name. Example:
`ecoli.get_frame_objects([genes[0]])[0]['common_name']`
(I believe the function only accepts a list and always return a list)

so:
```
dct = {k['common_name']:v for k,v in zip(ecoli.get_frame_objects(genes), genes)}
ecoli.get_frame_objects([dct['lacZ']])[0]['left_end_position'],\
ecoli.get_frame_objects([dct['lacZ']])[0]['right_end_position']
```

Best
